# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CubeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='cube',
        ),
        migrations.AddField(
            model_name='cubecontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubeapp.Content'),
        ),
        migrations.AddField(
            model_name='cubecontent',
            name='cube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubeapp.Cube'),
        ),
    ]
